// Engram service contract (walking-skeleton seam, locked in Phase 0).
//
// Ingest is the sync episodic append: cheap, durable, and the enqueue for the
// async write path (outbox, D12). event_id is REQUIRED — it is the client-
// supplied idempotency identity (D13); the server rejects an empty event_id
// with INVALID_ARGUMENT. proto3 cannot express required fields, so the
// requirement is enforced server-side and documented here.
//
// Search is the hybrid read path: BM25 + kNN fused by RRF (D1), scoped by
// tenancy filters (D16) and the bi-temporal current-state filter (D3).
//
// Authentication (Phase 3): every RPC is authenticated by a bearer token in
// the gRPC `authorization` metadata header, value "Bearer <raw-token>". A
// unary interceptor (the barricade) verifies the token, resolves the bound
// Identity{tenant_id, user_id, agent_id}, and injects it; unauthenticated
// calls are rejected with codes.Unauthenticated and an opaque message (no
// detail leak). The server derives tenancy/provenance from the resolved
// Identity, not from client-supplied fields, so a token cannot act outside
// its binding.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: engram.proto

package engrampb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// IngestRequest is one episodic event.
type IngestRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. Client-supplied idempotency identity (D13). Empty -> INVALID_ARGUMENT.
	EventId string `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	// Tenancy / provenance (D16); single-team values in the skeleton.
	TenantId     string   `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	TeamId       string   `protobuf:"bytes,3,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	Scope        string   `protobuf:"bytes,4,opt,name=scope,proto3" json:"scope,omitempty"`
	OwnerAgentId string   `protobuf:"bytes,5,opt,name=owner_agent_id,json=ownerAgentId,proto3" json:"owner_agent_id,omitempty"`
	SourceIds    []string `protobuf:"bytes,6,rep,name=source_ids,json=sourceIds,proto3" json:"source_ids,omitempty"`
	// Event classification (e.g. "tool_result", "conversation", "task").
	Kind string `protobuf:"bytes,7,opt,name=kind,proto3" json:"kind,omitempty"`
	// Raw event text; the extraction and BM25 target.
	Text string `protobuf:"bytes,8,opt,name=text,proto3" json:"text,omitempty"`
	// Real-world event time; the system stamps created_at itself (D3).
	OccurredAt    *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestRequest) Reset() {
	*x = IngestRequest{}
	mi := &file_engram_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestRequest) ProtoMessage() {}

func (x *IngestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_engram_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestRequest.ProtoReflect.Descriptor instead.
func (*IngestRequest) Descriptor() ([]byte, []int) {
	return file_engram_proto_rawDescGZIP(), []int{0}
}

func (x *IngestRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *IngestRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *IngestRequest) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

func (x *IngestRequest) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *IngestRequest) GetOwnerAgentId() string {
	if x != nil {
		return x.OwnerAgentId
	}
	return ""
}

func (x *IngestRequest) GetSourceIds() []string {
	if x != nil {
		return x.SourceIds
	}
	return nil
}

func (x *IngestRequest) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *IngestRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *IngestRequest) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

// IngestResponse acknowledges the durable append.
type IngestResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Durable episodic doc id.
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestResponse) Reset() {
	*x = IngestResponse{}
	mi := &file_engram_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestResponse) ProtoMessage() {}

func (x *IngestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_engram_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestResponse.ProtoReflect.Descriptor instead.
func (*IngestResponse) Descriptor() ([]byte, []int) {
	return file_engram_proto_rawDescGZIP(), []int{1}
}

func (x *IngestResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// SearchRequest is one hybrid retrieval query.
type SearchRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Query text; embedded for the kNN clause, matched for the BM25 clause.
	Query string `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	// Max fused results (default: server-chosen).
	K int32 `protobuf:"varint,2,opt,name=k,proto3" json:"k,omitempty"`
	// Tenancy scope filters (D16).
	TenantId string `protobuf:"bytes,3,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	UserId   string `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// Restrict to currently-valid facts (invalid_at == null AND expired_at ==
	// null — the bi-temporal current-state filter).
	ValidOnly     bool `protobuf:"varint,5,opt,name=valid_only,json=validOnly,proto3" json:"valid_only,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_engram_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_engram_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_engram_proto_rawDescGZIP(), []int{2}
}

func (x *SearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchRequest) GetK() int32 {
	if x != nil {
		return x.K
	}
	return 0
}

func (x *SearchRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *SearchRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SearchRequest) GetValidOnly() bool {
	if x != nil {
		return x.ValidOnly
	}
	return false
}

// Hit is one fused result.
type Hit struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Score float64                `protobuf:"fixed64,2,opt,name=score,proto3" json:"score,omitempty"`
	// Source index tier ("episodic" | "semantic").
	Source string `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	// Stored document rendered as JSON.
	FieldsJson    string `protobuf:"bytes,4,opt,name=fields_json,json=fieldsJson,proto3" json:"fields_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hit) Reset() {
	*x = Hit{}
	mi := &file_engram_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hit) ProtoMessage() {}

func (x *Hit) ProtoReflect() protoreflect.Message {
	mi := &file_engram_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hit.ProtoReflect.Descriptor instead.
func (*Hit) Descriptor() ([]byte, []int) {
	return file_engram_proto_rawDescGZIP(), []int{3}
}

func (x *Hit) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Hit) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *Hit) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Hit) GetFieldsJson() string {
	if x != nil {
		return x.FieldsJson
	}
	return ""
}

// SearchResponse is the single fused, ranked list.
type SearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hits          []*Hit                 `protobuf:"bytes,1,rep,name=hits,proto3" json:"hits,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_engram_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_engram_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_engram_proto_rawDescGZIP(), []int{4}
}

func (x *SearchResponse) GetHits() []*Hit {
	if x != nil {
		return x.Hits
	}
	return nil
}

// AuditRequest names one fact by its semantic doc id.
type AuditRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Semantic fact doc id (as returned in a search Hit).
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditRequest) Reset() {
	*x = AuditRequest{}
	mi := &file_engram_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditRequest) ProtoMessage() {}

func (x *AuditRequest) ProtoReflect() protoreflect.Message {
	mi := &file_engram_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditRequest.ProtoReflect.Descriptor instead.
func (*AuditRequest) Descriptor() ([]byte, []int) {
	return file_engram_proto_rawDescGZIP(), []int{5}
}

func (x *AuditRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// Provenance is who wrote a fact and from what (D6 provenance-as-ACL).
type Provenance struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	TenantId     string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	TeamId       string                 `protobuf:"bytes,2,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	Scope        string                 `protobuf:"bytes,3,opt,name=scope,proto3" json:"scope,omitempty"`
	OwnerAgentId string                 `protobuf:"bytes,4,opt,name=owner_agent_id,json=ownerAgentId,proto3" json:"owner_agent_id,omitempty"`
	// Episodic event ids this fact was extracted from.
	SourceIds []string `protobuf:"bytes,5,rep,name=source_ids,json=sourceIds,proto3" json:"source_ids,omitempty"`
	// Extraction pipeline version that produced it (D13).
	ExtractorVersion string `protobuf:"bytes,6,opt,name=extractor_version,json=extractorVersion,proto3" json:"extractor_version,omitempty"`
	// System append time of the audited version.
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Provenance) Reset() {
	*x = Provenance{}
	mi := &file_engram_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Provenance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Provenance) ProtoMessage() {}

func (x *Provenance) ProtoReflect() protoreflect.Message {
	mi := &file_engram_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Provenance.ProtoReflect.Descriptor instead.
func (*Provenance) Descriptor() ([]byte, []int) {
	return file_engram_proto_rawDescGZIP(), []int{6}
}

func (x *Provenance) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *Provenance) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

func (x *Provenance) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *Provenance) GetOwnerAgentId() string {
	if x != nil {
		return x.OwnerAgentId
	}
	return ""
}

func (x *Provenance) GetSourceIds() []string {
	if x != nil {
		return x.SourceIds
	}
	return nil
}

func (x *Provenance) GetExtractorVersion() string {
	if x != nil {
		return x.ExtractorVersion
	}
	return ""
}

func (x *Provenance) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// FactVersion is one record in a fact's bi-temporal chain.
type FactVersion struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Id         string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Subject    string                 `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	Predicate  string                 `protobuf:"bytes,3,opt,name=predicate,proto3" json:"predicate,omitempty"`
	Object     string                 `protobuf:"bytes,4,opt,name=object,proto3" json:"object,omitempty"`
	Statement  string                 `protobuf:"bytes,5,opt,name=statement,proto3" json:"statement,omitempty"`
	ContentKey string                 `protobuf:"bytes,6,opt,name=content_key,json=contentKey,proto3" json:"content_key,omitempty"`
	// Doc id of the version this one supersedes (UPDATE/INVALIDATE); "" for ADD.
	Supersedes string `protobuf:"bytes,7,opt,name=supersedes,proto3" json:"supersedes,omitempty"`
	// Valid time [valid_at, invalid_at): real-world truth interval.
	ValidAt   *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=valid_at,json=validAt,proto3" json:"valid_at,omitempty"`
	InvalidAt *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=invalid_at,json=invalidAt,proto3" json:"invalid_at,omitempty"`
	// Transaction time [created_at, expired_at): system currency interval.
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ExpiredAt     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=expired_at,json=expiredAt,proto3" json:"expired_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FactVersion) Reset() {
	*x = FactVersion{}
	mi := &file_engram_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FactVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FactVersion) ProtoMessage() {}

func (x *FactVersion) ProtoReflect() protoreflect.Message {
	mi := &file_engram_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FactVersion.ProtoReflect.Descriptor instead.
func (*FactVersion) Descriptor() ([]byte, []int) {
	return file_engram_proto_rawDescGZIP(), []int{7}
}

func (x *FactVersion) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FactVersion) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *FactVersion) GetPredicate() string {
	if x != nil {
		return x.Predicate
	}
	return ""
}

func (x *FactVersion) GetObject() string {
	if x != nil {
		return x.Object
	}
	return ""
}

func (x *FactVersion) GetStatement() string {
	if x != nil {
		return x.Statement
	}
	return ""
}

func (x *FactVersion) GetContentKey() string {
	if x != nil {
		return x.ContentKey
	}
	return ""
}

func (x *FactVersion) GetSupersedes() string {
	if x != nil {
		return x.Supersedes
	}
	return ""
}

func (x *FactVersion) GetValidAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ValidAt
	}
	return nil
}

func (x *FactVersion) GetInvalidAt() *timestamppb.Timestamp {
	if x != nil {
		return x.InvalidAt
	}
	return nil
}

func (x *FactVersion) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *FactVersion) GetExpiredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiredAt
	}
	return nil
}

// AuditResponse carries the target fact's provenance and its full history,
// ordered oldest-first by transaction then valid time.
type AuditResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Provenance    *Provenance            `protobuf:"bytes,1,opt,name=provenance,proto3" json:"provenance,omitempty"`
	Versions      []*FactVersion         `protobuf:"bytes,2,rep,name=versions,proto3" json:"versions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditResponse) Reset() {
	*x = AuditResponse{}
	mi := &file_engram_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditResponse) ProtoMessage() {}

func (x *AuditResponse) ProtoReflect() protoreflect.Message {
	mi := &file_engram_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditResponse.ProtoReflect.Descriptor instead.
func (*AuditResponse) Descriptor() ([]byte, []int) {
	return file_engram_proto_rawDescGZIP(), []int{8}
}

func (x *AuditResponse) GetProvenance() *Provenance {
	if x != nil {
		return x.Provenance
	}
	return nil
}

func (x *AuditResponse) GetVersions() []*FactVersion {
	if x != nil {
		return x.Versions
	}
	return nil
}

// ReadRequest names one record by the (id, source) pair a search Hit exposes.
type ReadRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Doc id exactly as surfaced by a search Hit. Empty -> INVALID_ARGUMENT.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Source tier the id lives in: "episodic" | "semantic". Selects the ONE
	// index consulted (never both). Empty or unknown -> INVALID_ARGUMENT;
	// "graph" -> UNIMPLEMENTED (a graph hit already carries its statement).
	Source        string `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadRequest) Reset() {
	*x = ReadRequest{}
	mi := &file_engram_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadRequest) ProtoMessage() {}

func (x *ReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_engram_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadRequest.ProtoReflect.Descriptor instead.
func (*ReadRequest) Descriptor() ([]byte, []int) {
	return file_engram_proto_rawDescGZIP(), []int{9}
}

func (x *ReadRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ReadRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

// EpisodicRecord is one full episodic event as Read returns it: the record's
// content projection ONLY. ACL/provenance fields (tenant_id, team_id, scope,
// owner_agent_id) are authorized against server-side and then deliberately
// projected away (fetch -> authorize -> project); embeddings and outbox
// worker state never leave the store.
type EpisodicRecord struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Doc id (the address the caller passed).
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Client-supplied idempotency identity (D13).
	EventId string `protobuf:"bytes,2,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	// Event classification (e.g. "tool_result", "conversation", "task").
	Kind string `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind,omitempty"`
	// Full, untruncated raw event text — the payload memory_read exists for.
	Text          string                 `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"`
	SourceIds     []string               `protobuf:"bytes,5,rep,name=source_ids,json=sourceIds,proto3" json:"source_ids,omitempty"`
	OccurredAt    *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EpisodicRecord) Reset() {
	*x = EpisodicRecord{}
	mi := &file_engram_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EpisodicRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EpisodicRecord) ProtoMessage() {}

func (x *EpisodicRecord) ProtoReflect() protoreflect.Message {
	mi := &file_engram_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EpisodicRecord.ProtoReflect.Descriptor instead.
func (*EpisodicRecord) Descriptor() ([]byte, []int) {
	return file_engram_proto_rawDescGZIP(), []int{10}
}

func (x *EpisodicRecord) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *EpisodicRecord) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *EpisodicRecord) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *EpisodicRecord) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *EpisodicRecord) GetSourceIds() []string {
	if x != nil {
		return x.SourceIds
	}
	return nil
}

func (x *EpisodicRecord) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

func (x *EpisodicRecord) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// ReadResponse carries exactly one record: the branch matching the requested
// source is populated, the other stays unset.
type ReadResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Echoes the request's source ("episodic" | "semantic").
	Source string `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	// Set when source=episodic.
	Episodic *EpisodicRecord `protobuf:"bytes,2,opt,name=episodic,proto3" json:"episodic,omitempty"`
	// Set when source=semantic: the TARGET version itself (a superseded id
	// returns that immutable version with its possibly-closed validity
	// interval), plus its provenance and full bi-temporal history — the Audit
	// contract, reused.
	Fact          *FactVersion   `protobuf:"bytes,3,opt,name=fact,proto3" json:"fact,omitempty"`
	Provenance    *Provenance    `protobuf:"bytes,4,opt,name=provenance,proto3" json:"provenance,omitempty"`
	Versions      []*FactVersion `protobuf:"bytes,5,rep,name=versions,proto3" json:"versions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadResponse) Reset() {
	*x = ReadResponse{}
	mi := &file_engram_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadResponse) ProtoMessage() {}

func (x *ReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_engram_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadResponse.ProtoReflect.Descriptor instead.
func (*ReadResponse) Descriptor() ([]byte, []int) {
	return file_engram_proto_rawDescGZIP(), []int{11}
}

func (x *ReadResponse) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *ReadResponse) GetEpisodic() *EpisodicRecord {
	if x != nil {
		return x.Episodic
	}
	return nil
}

func (x *ReadResponse) GetFact() *FactVersion {
	if x != nil {
		return x.Fact
	}
	return nil
}

func (x *ReadResponse) GetProvenance() *Provenance {
	if x != nil {
		return x.Provenance
	}
	return nil
}

func (x *ReadResponse) GetVersions() []*FactVersion {
	if x != nil {
		return x.Versions
	}
	return nil
}

// ExportRequest resumes a paged graph export. cursor is the opaque
// continuation token from the previous ExportResponse; empty starts from the
// beginning. Clients never construct or inspect a non-empty cursor.
type ExportRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cursor        string                 `protobuf:"bytes,1,opt,name=cursor,proto3" json:"cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportRequest) Reset() {
	*x = ExportRequest{}
	mi := &file_engram_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportRequest) ProtoMessage() {}

func (x *ExportRequest) ProtoReflect() protoreflect.Message {
	mi := &file_engram_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportRequest.ProtoReflect.Descriptor instead.
func (*ExportRequest) Descriptor() ([]byte, []int) {
	return file_engram_proto_rawDescGZIP(), []int{12}
}

func (x *ExportRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

// ExportEntity is one live, deduplicated graph entity in an export page —
// the structured record the CLI renders into an Obsidian note. Internal
// fields (embedding, name_key) are deliberately not exported; tenant_id is
// omitted because every record is the caller's own tenant by construction.
type ExportEntity struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Canonical display name (first-seen surface form).
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Every other merged surface form (dedup accounting).
	Aliases      []string `protobuf:"bytes,3,rep,name=aliases,proto3" json:"aliases,omitempty"`
	MentionCount int64    `protobuf:"varint,4,opt,name=mention_count,json=mentionCount,proto3" json:"mention_count,omitempty"`
	// Episodic event ids that contributed mentions (provenance).
	SourceIds []string `protobuf:"bytes,5,rep,name=source_ids,json=sourceIds,proto3" json:"source_ids,omitempty"`
	// Provenance / ACL fields (D6/D16).
	Scope         string                 `protobuf:"bytes,6,opt,name=scope,proto3" json:"scope,omitempty"`
	TeamId        string                 `protobuf:"bytes,7,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	OwnerAgentId  string                 `protobuf:"bytes,8,opt,name=owner_agent_id,json=ownerAgentId,proto3" json:"owner_agent_id,omitempty"`
	ValidAt       *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=valid_at,json=validAt,proto3" json:"valid_at,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportEntity) Reset() {
	*x = ExportEntity{}
	mi := &file_engram_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportEntity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportEntity) ProtoMessage() {}

func (x *ExportEntity) ProtoReflect() protoreflect.Message {
	mi := &file_engram_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportEntity.ProtoReflect.Descriptor instead.
func (*ExportEntity) Descriptor() ([]byte, []int) {
	return file_engram_proto_rawDescGZIP(), []int{13}
}

func (x *ExportEntity) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ExportEntity) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ExportEntity) GetAliases() []string {
	if x != nil {
		return x.Aliases
	}
	return nil
}

func (x *ExportEntity) GetMentionCount() int64 {
	if x != nil {
		return x.MentionCount
	}
	return 0
}

func (x *ExportEntity) GetSourceIds() []string {
	if x != nil {
		return x.SourceIds
	}
	return nil
}

func (x *ExportEntity) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *ExportEntity) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

func (x *ExportEntity) GetOwnerAgentId() string {
	if x != nil {
		return x.OwnerAgentId
	}
	return ""
}

func (x *ExportEntity) GetValidAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ValidAt
	}
	return nil
}

func (x *ExportEntity) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// ExportEdge is one live, predicate-typed relation in an export page. The
// endpoints are resolved entity ids (ExportEntity.id values).
type ExportEdge struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Id           string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FromEntityId string                 `protobuf:"bytes,2,opt,name=from_entity_id,json=fromEntityId,proto3" json:"from_entity_id,omitempty"`
	ToEntityId   string                 `protobuf:"bytes,3,opt,name=to_entity_id,json=toEntityId,proto3" json:"to_entity_id,omitempty"`
	Predicate    string                 `protobuf:"bytes,4,opt,name=predicate,proto3" json:"predicate,omitempty"`
	// Natural-language rendering of the relation (from the source fact).
	Statement     string                 `protobuf:"bytes,5,opt,name=statement,proto3" json:"statement,omitempty"`
	SourceIds     []string               `protobuf:"bytes,6,rep,name=source_ids,json=sourceIds,proto3" json:"source_ids,omitempty"`
	Scope         string                 `protobuf:"bytes,7,opt,name=scope,proto3" json:"scope,omitempty"`
	TeamId        string                 `protobuf:"bytes,8,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	OwnerAgentId  string                 `protobuf:"bytes,9,opt,name=owner_agent_id,json=ownerAgentId,proto3" json:"owner_agent_id,omitempty"`
	ValidAt       *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=valid_at,json=validAt,proto3" json:"valid_at,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportEdge) Reset() {
	*x = ExportEdge{}
	mi := &file_engram_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportEdge) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportEdge) ProtoMessage() {}

func (x *ExportEdge) ProtoReflect() protoreflect.Message {
	mi := &file_engram_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportEdge.ProtoReflect.Descriptor instead.
func (*ExportEdge) Descriptor() ([]byte, []int) {
	return file_engram_proto_rawDescGZIP(), []int{14}
}

func (x *ExportEdge) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ExportEdge) GetFromEntityId() string {
	if x != nil {
		return x.FromEntityId
	}
	return ""
}

func (x *ExportEdge) GetToEntityId() string {
	if x != nil {
		return x.ToEntityId
	}
	return ""
}

func (x *ExportEdge) GetPredicate() string {
	if x != nil {
		return x.Predicate
	}
	return ""
}

func (x *ExportEdge) GetStatement() string {
	if x != nil {
		return x.Statement
	}
	return ""
}

func (x *ExportEdge) GetSourceIds() []string {
	if x != nil {
		return x.SourceIds
	}
	return nil
}

func (x *ExportEdge) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *ExportEdge) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

func (x *ExportEdge) GetOwnerAgentId() string {
	if x != nil {
		return x.OwnerAgentId
	}
	return ""
}

func (x *ExportEdge) GetValidAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ValidAt
	}
	return nil
}

func (x *ExportEdge) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// ExportResponse is one bounded page: entities first, then edges (a page may
// carry both when the entity tier exhausts mid-call). An empty next_cursor
// means the export is complete.
type ExportResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entities      []*ExportEntity        `protobuf:"bytes,1,rep,name=entities,proto3" json:"entities,omitempty"`
	Edges         []*ExportEdge          `protobuf:"bytes,2,rep,name=edges,proto3" json:"edges,omitempty"`
	NextCursor    string                 `protobuf:"bytes,3,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportResponse) Reset() {
	*x = ExportResponse{}
	mi := &file_engram_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportResponse) ProtoMessage() {}

func (x *ExportResponse) ProtoReflect() protoreflect.Message {
	mi := &file_engram_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportResponse.ProtoReflect.Descriptor instead.
func (*ExportResponse) Descriptor() ([]byte, []int) {
	return file_engram_proto_rawDescGZIP(), []int{15}
}

func (x *ExportResponse) GetEntities() []*ExportEntity {
	if x != nil {
		return x.Entities
	}
	return nil
}

func (x *ExportResponse) GetEdges() []*ExportEdge {
	if x != nil {
		return x.Edges
	}
	return nil
}

func (x *ExportResponse) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

// StatusRequest is empty; the caller is identified by the bearer token.
type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_engram_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_engram_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_engram_proto_rawDescGZIP(), []int{16}
}

// StatusResponse reports liveness, the resolved identity, and tier counts.
type StatusResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// healthy is true when the backing store answered the count probe.
	Healthy bool `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	// Resolved identity of the caller (from the verified token).
	TenantId string `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	UserId   string `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AgentId  string `protobuf:"bytes,4,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	// Coarse per-tier document counts for the caller's tenant.
	EpisodicCount int64 `protobuf:"varint,5,opt,name=episodic_count,json=episodicCount,proto3" json:"episodic_count,omitempty"`
	SemanticCount int64 `protobuf:"varint,6,opt,name=semantic_count,json=semanticCount,proto3" json:"semantic_count,omitempty"`
	// OpenSearch version line the server is pinned to (D14).
	OpensearchVersion string `protobuf:"bytes,7,opt,name=opensearch_version,json=opensearchVersion,proto3" json:"opensearch_version,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_engram_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_engram_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_engram_proto_rawDescGZIP(), []int{17}
}

func (x *StatusResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *StatusResponse) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *StatusResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *StatusResponse) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *StatusResponse) GetEpisodicCount() int64 {
	if x != nil {
		return x.EpisodicCount
	}
	return 0
}

func (x *StatusResponse) GetSemanticCount() int64 {
	if x != nil {
		return x.SemanticCount
	}
	return 0
}

func (x *StatusResponse) GetOpensearchVersion() string {
	if x != nil {
		return x.OpensearchVersion
	}
	return ""
}

var File_engram_proto protoreflect.FileDescriptor

const file_engram_proto_rawDesc = "" +
	"\n" +
	"\fengram.proto\x12\tengram.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa0\x02\n" +
	"\rIngestRequest\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x17\n" +
	"\ateam_id\x18\x03 \x01(\tR\x06teamId\x12\x14\n" +
	"\x05scope\x18\x04 \x01(\tR\x05scope\x12$\n" +
	"\x0eowner_agent_id\x18\x05 \x01(\tR\fownerAgentId\x12\x1d\n" +
	"\n" +
	"source_ids\x18\x06 \x03(\tR\tsourceIds\x12\x12\n" +
	"\x04kind\x18\a \x01(\tR\x04kind\x12\x12\n" +
	"\x04text\x18\b \x01(\tR\x04text\x12;\n" +
	"\voccurred_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt\" \n" +
	"\x0eIngestResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x88\x01\n" +
	"\rSearchRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\f\n" +
	"\x01k\x18\x02 \x01(\x05R\x01k\x12\x1b\n" +
	"\ttenant_id\x18\x03 \x01(\tR\btenantId\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"valid_only\x18\x05 \x01(\bR\tvalidOnly\"d\n" +
	"\x03Hit\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x01R\x05score\x12\x16\n" +
	"\x06source\x18\x03 \x01(\tR\x06source\x12\x1f\n" +
	"\vfields_json\x18\x04 \x01(\tR\n" +
	"fieldsJson\"4\n" +
	"\x0eSearchResponse\x12\"\n" +
	"\x04hits\x18\x01 \x03(\v2\x0e.engram.v1.HitR\x04hits\"\x1e\n" +
	"\fAuditRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x85\x02\n" +
	"\n" +
	"Provenance\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x17\n" +
	"\ateam_id\x18\x02 \x01(\tR\x06teamId\x12\x14\n" +
	"\x05scope\x18\x03 \x01(\tR\x05scope\x12$\n" +
	"\x0eowner_agent_id\x18\x04 \x01(\tR\fownerAgentId\x12\x1d\n" +
	"\n" +
	"source_ids\x18\x05 \x03(\tR\tsourceIds\x12+\n" +
	"\x11extractor_version\x18\x06 \x01(\tR\x10extractorVersion\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xb4\x03\n" +
	"\vFactVersion\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\asubject\x18\x02 \x01(\tR\asubject\x12\x1c\n" +
	"\tpredicate\x18\x03 \x01(\tR\tpredicate\x12\x16\n" +
	"\x06object\x18\x04 \x01(\tR\x06object\x12\x1c\n" +
	"\tstatement\x18\x05 \x01(\tR\tstatement\x12\x1f\n" +
	"\vcontent_key\x18\x06 \x01(\tR\n" +
	"contentKey\x12\x1e\n" +
	"\n" +
	"supersedes\x18\a \x01(\tR\n" +
	"supersedes\x125\n" +
	"\bvalid_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\avalidAt\x129\n" +
	"\n" +
	"invalid_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tinvalidAt\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"expired_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\texpiredAt\"z\n" +
	"\rAuditResponse\x125\n" +
	"\n" +
	"provenance\x18\x01 \x01(\v2\x15.engram.v1.ProvenanceR\n" +
	"provenance\x122\n" +
	"\bversions\x18\x02 \x03(\v2\x16.engram.v1.FactVersionR\bversions\"5\n" +
	"\vReadRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\"\xfa\x01\n" +
	"\x0eEpisodicRecord\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bevent_id\x18\x02 \x01(\tR\aeventId\x12\x12\n" +
	"\x04kind\x18\x03 \x01(\tR\x04kind\x12\x12\n" +
	"\x04text\x18\x04 \x01(\tR\x04text\x12\x1d\n" +
	"\n" +
	"source_ids\x18\x05 \x03(\tR\tsourceIds\x12;\n" +
	"\voccurred_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xf4\x01\n" +
	"\fReadResponse\x12\x16\n" +
	"\x06source\x18\x01 \x01(\tR\x06source\x125\n" +
	"\bepisodic\x18\x02 \x01(\v2\x19.engram.v1.EpisodicRecordR\bepisodic\x12*\n" +
	"\x04fact\x18\x03 \x01(\v2\x16.engram.v1.FactVersionR\x04fact\x125\n" +
	"\n" +
	"provenance\x18\x04 \x01(\v2\x15.engram.v1.ProvenanceR\n" +
	"provenance\x122\n" +
	"\bversions\x18\x05 \x03(\v2\x16.engram.v1.FactVersionR\bversions\"'\n" +
	"\rExportRequest\x12\x16\n" +
	"\x06cursor\x18\x01 \x01(\tR\x06cursor\"\xd7\x02\n" +
	"\fExportEntity\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aaliases\x18\x03 \x03(\tR\aaliases\x12#\n" +
	"\rmention_count\x18\x04 \x01(\x03R\fmentionCount\x12\x1d\n" +
	"\n" +
	"source_ids\x18\x05 \x03(\tR\tsourceIds\x12\x14\n" +
	"\x05scope\x18\x06 \x01(\tR\x05scope\x12\x17\n" +
	"\ateam_id\x18\a \x01(\tR\x06teamId\x12$\n" +
	"\x0eowner_agent_id\x18\b \x01(\tR\fownerAgentId\x125\n" +
	"\bvalid_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\avalidAt\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\x86\x03\n" +
	"\n" +
	"ExportEdge\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12$\n" +
	"\x0efrom_entity_id\x18\x02 \x01(\tR\ffromEntityId\x12 \n" +
	"\fto_entity_id\x18\x03 \x01(\tR\n" +
	"toEntityId\x12\x1c\n" +
	"\tpredicate\x18\x04 \x01(\tR\tpredicate\x12\x1c\n" +
	"\tstatement\x18\x05 \x01(\tR\tstatement\x12\x1d\n" +
	"\n" +
	"source_ids\x18\x06 \x03(\tR\tsourceIds\x12\x14\n" +
	"\x05scope\x18\a \x01(\tR\x05scope\x12\x17\n" +
	"\ateam_id\x18\b \x01(\tR\x06teamId\x12$\n" +
	"\x0eowner_agent_id\x18\t \x01(\tR\fownerAgentId\x125\n" +
	"\bvalid_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\avalidAt\x129\n" +
	"\n" +
	"created_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\x93\x01\n" +
	"\x0eExportResponse\x123\n" +
	"\bentities\x18\x01 \x03(\v2\x17.engram.v1.ExportEntityR\bentities\x12+\n" +
	"\x05edges\x18\x02 \x03(\v2\x15.engram.v1.ExportEdgeR\x05edges\x12\x1f\n" +
	"\vnext_cursor\x18\x03 \x01(\tR\n" +
	"nextCursor\"\x0f\n" +
	"\rStatusRequest\"\xf8\x01\n" +
	"\x0eStatusResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x19\n" +
	"\bagent_id\x18\x04 \x01(\tR\aagentId\x12%\n" +
	"\x0eepisodic_count\x18\x05 \x01(\x03R\repisodicCount\x12%\n" +
	"\x0esemantic_count\x18\x06 \x01(\x03R\rsemanticCount\x12-\n" +
	"\x12opensearch_version\x18\a \x01(\tR\x11opensearchVersion2\xf9\x02\n" +
	"\x06Engram\x12=\n" +
	"\x06Ingest\x12\x18.engram.v1.IngestRequest\x1a\x19.engram.v1.IngestResponse\x12=\n" +
	"\x06Search\x12\x18.engram.v1.SearchRequest\x1a\x19.engram.v1.SearchResponse\x12=\n" +
	"\x06Status\x12\x18.engram.v1.StatusRequest\x1a\x19.engram.v1.StatusResponse\x12:\n" +
	"\x05Audit\x12\x17.engram.v1.AuditRequest\x1a\x18.engram.v1.AuditResponse\x127\n" +
	"\x04Read\x12\x16.engram.v1.ReadRequest\x1a\x17.engram.v1.ReadResponse\x12=\n" +
	"\x06Export\x12\x18.engram.v1.ExportRequest\x1a\x19.engram.v1.ExportResponseB+Z)github.com/ryanthedev/engram/api/engrampbb\x06proto3"

var (
	file_engram_proto_rawDescOnce sync.Once
	file_engram_proto_rawDescData []byte
)

func file_engram_proto_rawDescGZIP() []byte {
	file_engram_proto_rawDescOnce.Do(func() {
		file_engram_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_engram_proto_rawDesc), len(file_engram_proto_rawDesc)))
	})
	return file_engram_proto_rawDescData
}

var file_engram_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_engram_proto_goTypes = []any{
	(*IngestRequest)(nil),         // 0: engram.v1.IngestRequest
	(*IngestResponse)(nil),        // 1: engram.v1.IngestResponse
	(*SearchRequest)(nil),         // 2: engram.v1.SearchRequest
	(*Hit)(nil),                   // 3: engram.v1.Hit
	(*SearchResponse)(nil),        // 4: engram.v1.SearchResponse
	(*AuditRequest)(nil),          // 5: engram.v1.AuditRequest
	(*Provenance)(nil),            // 6: engram.v1.Provenance
	(*FactVersion)(nil),           // 7: engram.v1.FactVersion
	(*AuditResponse)(nil),         // 8: engram.v1.AuditResponse
	(*ReadRequest)(nil),           // 9: engram.v1.ReadRequest
	(*EpisodicRecord)(nil),        // 10: engram.v1.EpisodicRecord
	(*ReadResponse)(nil),          // 11: engram.v1.ReadResponse
	(*ExportRequest)(nil),         // 12: engram.v1.ExportRequest
	(*ExportEntity)(nil),          // 13: engram.v1.ExportEntity
	(*ExportEdge)(nil),            // 14: engram.v1.ExportEdge
	(*ExportResponse)(nil),        // 15: engram.v1.ExportResponse
	(*StatusRequest)(nil),         // 16: engram.v1.StatusRequest
	(*StatusResponse)(nil),        // 17: engram.v1.StatusResponse
	(*timestamppb.Timestamp)(nil), // 18: google.protobuf.Timestamp
}
var file_engram_proto_depIdxs = []int32{
	18, // 0: engram.v1.IngestRequest.occurred_at:type_name -> google.protobuf.Timestamp
	3,  // 1: engram.v1.SearchResponse.hits:type_name -> engram.v1.Hit
	18, // 2: engram.v1.Provenance.created_at:type_name -> google.protobuf.Timestamp
	18, // 3: engram.v1.FactVersion.valid_at:type_name -> google.protobuf.Timestamp
	18, // 4: engram.v1.FactVersion.invalid_at:type_name -> google.protobuf.Timestamp
	18, // 5: engram.v1.FactVersion.created_at:type_name -> google.protobuf.Timestamp
	18, // 6: engram.v1.FactVersion.expired_at:type_name -> google.protobuf.Timestamp
	6,  // 7: engram.v1.AuditResponse.provenance:type_name -> engram.v1.Provenance
	7,  // 8: engram.v1.AuditResponse.versions:type_name -> engram.v1.FactVersion
	18, // 9: engram.v1.EpisodicRecord.occurred_at:type_name -> google.protobuf.Timestamp
	18, // 10: engram.v1.EpisodicRecord.created_at:type_name -> google.protobuf.Timestamp
	10, // 11: engram.v1.ReadResponse.episodic:type_name -> engram.v1.EpisodicRecord
	7,  // 12: engram.v1.ReadResponse.fact:type_name -> engram.v1.FactVersion
	6,  // 13: engram.v1.ReadResponse.provenance:type_name -> engram.v1.Provenance
	7,  // 14: engram.v1.ReadResponse.versions:type_name -> engram.v1.FactVersion
	18, // 15: engram.v1.ExportEntity.valid_at:type_name -> google.protobuf.Timestamp
	18, // 16: engram.v1.ExportEntity.created_at:type_name -> google.protobuf.Timestamp
	18, // 17: engram.v1.ExportEdge.valid_at:type_name -> google.protobuf.Timestamp
	18, // 18: engram.v1.ExportEdge.created_at:type_name -> google.protobuf.Timestamp
	13, // 19: engram.v1.ExportResponse.entities:type_name -> engram.v1.ExportEntity
	14, // 20: engram.v1.ExportResponse.edges:type_name -> engram.v1.ExportEdge
	0,  // 21: engram.v1.Engram.Ingest:input_type -> engram.v1.IngestRequest
	2,  // 22: engram.v1.Engram.Search:input_type -> engram.v1.SearchRequest
	16, // 23: engram.v1.Engram.Status:input_type -> engram.v1.StatusRequest
	5,  // 24: engram.v1.Engram.Audit:input_type -> engram.v1.AuditRequest
	9,  // 25: engram.v1.Engram.Read:input_type -> engram.v1.ReadRequest
	12, // 26: engram.v1.Engram.Export:input_type -> engram.v1.ExportRequest
	1,  // 27: engram.v1.Engram.Ingest:output_type -> engram.v1.IngestResponse
	4,  // 28: engram.v1.Engram.Search:output_type -> engram.v1.SearchResponse
	17, // 29: engram.v1.Engram.Status:output_type -> engram.v1.StatusResponse
	8,  // 30: engram.v1.Engram.Audit:output_type -> engram.v1.AuditResponse
	11, // 31: engram.v1.Engram.Read:output_type -> engram.v1.ReadResponse
	15, // 32: engram.v1.Engram.Export:output_type -> engram.v1.ExportResponse
	27, // [27:33] is the sub-list for method output_type
	21, // [21:27] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_engram_proto_init() }
func file_engram_proto_init() {
	if File_engram_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_engram_proto_rawDesc), len(file_engram_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_engram_proto_goTypes,
		DependencyIndexes: file_engram_proto_depIdxs,
		MessageInfos:      file_engram_proto_msgTypes,
	}.Build()
	File_engram_proto = out.File
	file_engram_proto_goTypes = nil
	file_engram_proto_depIdxs = nil
}
