// Engram service contract (walking-skeleton seam, locked in Phase 0).
//
// Ingest is the sync episodic append: cheap, durable, and the enqueue for the
// async write path (outbox, D12). event_id is REQUIRED — it is the client-
// supplied idempotency identity (D13); the server rejects an empty event_id
// with INVALID_ARGUMENT. proto3 cannot express required fields, so the
// requirement is enforced server-side and documented here.
//
// Search is the hybrid read path: BM25 + kNN fused by RRF (D1), scoped by
// tenancy filters (D16) and the bi-temporal current-state filter (D3).
//
// Authentication (Phase 3): every RPC is authenticated by a bearer token in
// the gRPC `authorization` metadata header, value "Bearer <raw-token>". A
// unary interceptor (the barricade) verifies the token, resolves the bound
// Identity{tenant_id, user_id, agent_id}, and injects it; unauthenticated
// calls are rejected with codes.Unauthenticated and an opaque message (no
// detail leak). The server derives tenancy/provenance from the resolved
// Identity, not from client-supplied fields, so a token cannot act outside
// its binding.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: engram.proto

package engrampb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// IngestRequest is one episodic event.
type IngestRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. Client-supplied idempotency identity (D13). Empty -> INVALID_ARGUMENT.
	EventId string `protobuf:"bytes,1,opt,name=event_id,json=eventId,proto3" json:"event_id,omitempty"`
	// Tenancy / provenance (D16); single-team values in the skeleton.
	TenantId     string   `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	TeamId       string   `protobuf:"bytes,3,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	Scope        string   `protobuf:"bytes,4,opt,name=scope,proto3" json:"scope,omitempty"`
	OwnerAgentId string   `protobuf:"bytes,5,opt,name=owner_agent_id,json=ownerAgentId,proto3" json:"owner_agent_id,omitempty"`
	SourceIds    []string `protobuf:"bytes,6,rep,name=source_ids,json=sourceIds,proto3" json:"source_ids,omitempty"`
	// Event classification (e.g. "tool_result", "conversation", "task").
	Kind string `protobuf:"bytes,7,opt,name=kind,proto3" json:"kind,omitempty"`
	// Raw event text; the extraction and BM25 target.
	Text string `protobuf:"bytes,8,opt,name=text,proto3" json:"text,omitempty"`
	// Real-world event time; the system stamps created_at itself (D3).
	OccurredAt    *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=occurred_at,json=occurredAt,proto3" json:"occurred_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestRequest) Reset() {
	*x = IngestRequest{}
	mi := &file_engram_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestRequest) ProtoMessage() {}

func (x *IngestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_engram_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestRequest.ProtoReflect.Descriptor instead.
func (*IngestRequest) Descriptor() ([]byte, []int) {
	return file_engram_proto_rawDescGZIP(), []int{0}
}

func (x *IngestRequest) GetEventId() string {
	if x != nil {
		return x.EventId
	}
	return ""
}

func (x *IngestRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *IngestRequest) GetTeamId() string {
	if x != nil {
		return x.TeamId
	}
	return ""
}

func (x *IngestRequest) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *IngestRequest) GetOwnerAgentId() string {
	if x != nil {
		return x.OwnerAgentId
	}
	return ""
}

func (x *IngestRequest) GetSourceIds() []string {
	if x != nil {
		return x.SourceIds
	}
	return nil
}

func (x *IngestRequest) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *IngestRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *IngestRequest) GetOccurredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.OccurredAt
	}
	return nil
}

// IngestResponse acknowledges the durable append.
type IngestResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Durable episodic doc id.
	Id            string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestResponse) Reset() {
	*x = IngestResponse{}
	mi := &file_engram_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestResponse) ProtoMessage() {}

func (x *IngestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_engram_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestResponse.ProtoReflect.Descriptor instead.
func (*IngestResponse) Descriptor() ([]byte, []int) {
	return file_engram_proto_rawDescGZIP(), []int{1}
}

func (x *IngestResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

// SearchRequest is one hybrid retrieval query.
type SearchRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Query text; embedded for the kNN clause, matched for the BM25 clause.
	Query string `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	// Max fused results (default: server-chosen).
	K int32 `protobuf:"varint,2,opt,name=k,proto3" json:"k,omitempty"`
	// Tenancy scope filters (D16).
	TenantId string `protobuf:"bytes,3,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	UserId   string `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// Restrict to currently-valid facts (invalid_at == null AND expired_at ==
	// null — the bi-temporal current-state filter).
	ValidOnly     bool `protobuf:"varint,5,opt,name=valid_only,json=validOnly,proto3" json:"valid_only,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_engram_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_engram_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_engram_proto_rawDescGZIP(), []int{2}
}

func (x *SearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchRequest) GetK() int32 {
	if x != nil {
		return x.K
	}
	return 0
}

func (x *SearchRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *SearchRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SearchRequest) GetValidOnly() bool {
	if x != nil {
		return x.ValidOnly
	}
	return false
}

// Hit is one fused result.
type Hit struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Id    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Score float64                `protobuf:"fixed64,2,opt,name=score,proto3" json:"score,omitempty"`
	// Source index tier ("episodic" | "semantic").
	Source string `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	// Stored document rendered as JSON.
	FieldsJson    string `protobuf:"bytes,4,opt,name=fields_json,json=fieldsJson,proto3" json:"fields_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hit) Reset() {
	*x = Hit{}
	mi := &file_engram_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hit) ProtoMessage() {}

func (x *Hit) ProtoReflect() protoreflect.Message {
	mi := &file_engram_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hit.ProtoReflect.Descriptor instead.
func (*Hit) Descriptor() ([]byte, []int) {
	return file_engram_proto_rawDescGZIP(), []int{3}
}

func (x *Hit) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Hit) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *Hit) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Hit) GetFieldsJson() string {
	if x != nil {
		return x.FieldsJson
	}
	return ""
}

// SearchResponse is the single fused, ranked list.
type SearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hits          []*Hit                 `protobuf:"bytes,1,rep,name=hits,proto3" json:"hits,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_engram_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_engram_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_engram_proto_rawDescGZIP(), []int{4}
}

func (x *SearchResponse) GetHits() []*Hit {
	if x != nil {
		return x.Hits
	}
	return nil
}

// StatusRequest is empty; the caller is identified by the bearer token.
type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_engram_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_engram_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_engram_proto_rawDescGZIP(), []int{5}
}

// StatusResponse reports liveness, the resolved identity, and tier counts.
type StatusResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// healthy is true when the backing store answered the count probe.
	Healthy bool `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	// Resolved identity of the caller (from the verified token).
	TenantId string `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	UserId   string `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	AgentId  string `protobuf:"bytes,4,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	// Coarse per-tier document counts for the caller's tenant.
	EpisodicCount int64 `protobuf:"varint,5,opt,name=episodic_count,json=episodicCount,proto3" json:"episodic_count,omitempty"`
	SemanticCount int64 `protobuf:"varint,6,opt,name=semantic_count,json=semanticCount,proto3" json:"semantic_count,omitempty"`
	// OpenSearch version line the server is pinned to (D14).
	OpensearchVersion string `protobuf:"bytes,7,opt,name=opensearch_version,json=opensearchVersion,proto3" json:"opensearch_version,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_engram_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_engram_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_engram_proto_rawDescGZIP(), []int{6}
}

func (x *StatusResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *StatusResponse) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *StatusResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *StatusResponse) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *StatusResponse) GetEpisodicCount() int64 {
	if x != nil {
		return x.EpisodicCount
	}
	return 0
}

func (x *StatusResponse) GetSemanticCount() int64 {
	if x != nil {
		return x.SemanticCount
	}
	return 0
}

func (x *StatusResponse) GetOpensearchVersion() string {
	if x != nil {
		return x.OpensearchVersion
	}
	return ""
}

var File_engram_proto protoreflect.FileDescriptor

const file_engram_proto_rawDesc = "" +
	"\n" +
	"\fengram.proto\x12\tengram.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa0\x02\n" +
	"\rIngestRequest\x12\x19\n" +
	"\bevent_id\x18\x01 \x01(\tR\aeventId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x17\n" +
	"\ateam_id\x18\x03 \x01(\tR\x06teamId\x12\x14\n" +
	"\x05scope\x18\x04 \x01(\tR\x05scope\x12$\n" +
	"\x0eowner_agent_id\x18\x05 \x01(\tR\fownerAgentId\x12\x1d\n" +
	"\n" +
	"source_ids\x18\x06 \x03(\tR\tsourceIds\x12\x12\n" +
	"\x04kind\x18\a \x01(\tR\x04kind\x12\x12\n" +
	"\x04text\x18\b \x01(\tR\x04text\x12;\n" +
	"\voccurred_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"occurredAt\" \n" +
	"\x0eIngestResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x88\x01\n" +
	"\rSearchRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\f\n" +
	"\x01k\x18\x02 \x01(\x05R\x01k\x12\x1b\n" +
	"\ttenant_id\x18\x03 \x01(\tR\btenantId\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"valid_only\x18\x05 \x01(\bR\tvalidOnly\"d\n" +
	"\x03Hit\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x01R\x05score\x12\x16\n" +
	"\x06source\x18\x03 \x01(\tR\x06source\x12\x1f\n" +
	"\vfields_json\x18\x04 \x01(\tR\n" +
	"fieldsJson\"4\n" +
	"\x0eSearchResponse\x12\"\n" +
	"\x04hits\x18\x01 \x03(\v2\x0e.engram.v1.HitR\x04hits\"\x0f\n" +
	"\rStatusRequest\"\xf8\x01\n" +
	"\x0eStatusResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x19\n" +
	"\bagent_id\x18\x04 \x01(\tR\aagentId\x12%\n" +
	"\x0eepisodic_count\x18\x05 \x01(\x03R\repisodicCount\x12%\n" +
	"\x0esemantic_count\x18\x06 \x01(\x03R\rsemanticCount\x12-\n" +
	"\x12opensearch_version\x18\a \x01(\tR\x11opensearchVersion2\xc5\x01\n" +
	"\x06Engram\x12=\n" +
	"\x06Ingest\x12\x18.engram.v1.IngestRequest\x1a\x19.engram.v1.IngestResponse\x12=\n" +
	"\x06Search\x12\x18.engram.v1.SearchRequest\x1a\x19.engram.v1.SearchResponse\x12=\n" +
	"\x06Status\x12\x18.engram.v1.StatusRequest\x1a\x19.engram.v1.StatusResponseB+Z)github.com/ryanthedev/engram/api/engrampbb\x06proto3"

var (
	file_engram_proto_rawDescOnce sync.Once
	file_engram_proto_rawDescData []byte
)

func file_engram_proto_rawDescGZIP() []byte {
	file_engram_proto_rawDescOnce.Do(func() {
		file_engram_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_engram_proto_rawDesc), len(file_engram_proto_rawDesc)))
	})
	return file_engram_proto_rawDescData
}

var file_engram_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_engram_proto_goTypes = []any{
	(*IngestRequest)(nil),         // 0: engram.v1.IngestRequest
	(*IngestResponse)(nil),        // 1: engram.v1.IngestResponse
	(*SearchRequest)(nil),         // 2: engram.v1.SearchRequest
	(*Hit)(nil),                   // 3: engram.v1.Hit
	(*SearchResponse)(nil),        // 4: engram.v1.SearchResponse
	(*StatusRequest)(nil),         // 5: engram.v1.StatusRequest
	(*StatusResponse)(nil),        // 6: engram.v1.StatusResponse
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
}
var file_engram_proto_depIdxs = []int32{
	7, // 0: engram.v1.IngestRequest.occurred_at:type_name -> google.protobuf.Timestamp
	3, // 1: engram.v1.SearchResponse.hits:type_name -> engram.v1.Hit
	0, // 2: engram.v1.Engram.Ingest:input_type -> engram.v1.IngestRequest
	2, // 3: engram.v1.Engram.Search:input_type -> engram.v1.SearchRequest
	5, // 4: engram.v1.Engram.Status:input_type -> engram.v1.StatusRequest
	1, // 5: engram.v1.Engram.Ingest:output_type -> engram.v1.IngestResponse
	4, // 6: engram.v1.Engram.Search:output_type -> engram.v1.SearchResponse
	6, // 7: engram.v1.Engram.Status:output_type -> engram.v1.StatusResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_engram_proto_init() }
func file_engram_proto_init() {
	if File_engram_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_engram_proto_rawDesc), len(file_engram_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_engram_proto_goTypes,
		DependencyIndexes: file_engram_proto_depIdxs,
		MessageInfos:      file_engram_proto_msgTypes,
	}.Build()
	File_engram_proto = out.File
	file_engram_proto_goTypes = nil
	file_engram_proto_depIdxs = nil
}
