// Engram service contract (walking-skeleton seam, locked in Phase 0).
//
// Ingest is the sync episodic append: cheap, durable, and the enqueue for the
// async write path (outbox, D12). event_id is REQUIRED — it is the client-
// supplied idempotency identity (D13); the server rejects an empty event_id
// with INVALID_ARGUMENT. proto3 cannot express required fields, so the
// requirement is enforced server-side and documented here.
//
// Search is the hybrid read path: BM25 + kNN fused by RRF (D1), scoped by
// tenancy filters (D16) and the bi-temporal current-state filter (D3).
//
// Authentication (Phase 3): every RPC is authenticated by a bearer token in
// the gRPC `authorization` metadata header, value "Bearer <raw-token>". A
// unary interceptor (the barricade) verifies the token, resolves the bound
// Identity{tenant_id, user_id, agent_id}, and injects it; unauthenticated
// calls are rejected with codes.Unauthenticated and an opaque message (no
// detail leak). The server derives tenancy/provenance from the resolved
// Identity, not from client-supplied fields, so a token cannot act outside
// its binding.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: engram.proto

package engrampb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Engram_Ingest_FullMethodName = "/engram.v1.Engram/Ingest"
	Engram_Search_FullMethodName = "/engram.v1.Engram/Search"
	Engram_Status_FullMethodName = "/engram.v1.Engram/Status"
	Engram_Audit_FullMethodName  = "/engram.v1.Engram/Audit"
)

// EngramClient is the client API for Engram service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Engram is the agent-memory service: sync episodic ingest and hybrid search.
type EngramClient interface {
	// Ingest durably appends one event to episodic memory and returns its
	// storage id. The append is the enqueue: extraction and reconciliation
	// happen asynchronously (D4/D12). event_id is required; replays of the
	// same event_id are idempotent end-to-end via the extraction ledger (D13).
	Ingest(ctx context.Context, in *IngestRequest, opts ...grpc.CallOption) (*IngestResponse, error)
	// Search runs one hybrid query (BM25 + kNN -> RRF) and returns a single
	// fused, ranked hit list.
	Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error)
	// Status reports server health, the caller's resolved identity, and coarse
	// tier document counts — the backing RPC for `engram status` and the MCP
	// memory_status tool. It requires a valid token like every other call.
	Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	// Audit returns a fact's provenance (who wrote it, from what) and its full
	// bi-temporal version history (Phase 4, DW-4.6) — the backing RPC for
	// `engram audit <id>`. The caller must be authorized to READ the target
	// fact; an unauthorized or unknown id returns NOT_FOUND (no existence
	// oracle). Scope enforcement applies here exactly as it does to search.
	Audit(ctx context.Context, in *AuditRequest, opts ...grpc.CallOption) (*AuditResponse, error)
}

type engramClient struct {
	cc grpc.ClientConnInterface
}

func NewEngramClient(cc grpc.ClientConnInterface) EngramClient {
	return &engramClient{cc}
}

func (c *engramClient) Ingest(ctx context.Context, in *IngestRequest, opts ...grpc.CallOption) (*IngestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IngestResponse)
	err := c.cc.Invoke(ctx, Engram_Ingest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engramClient) Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchResponse)
	err := c.cc.Invoke(ctx, Engram_Search_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engramClient) Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, Engram_Status_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engramClient) Audit(ctx context.Context, in *AuditRequest, opts ...grpc.CallOption) (*AuditResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuditResponse)
	err := c.cc.Invoke(ctx, Engram_Audit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EngramServer is the server API for Engram service.
// All implementations must embed UnimplementedEngramServer
// for forward compatibility.
//
// Engram is the agent-memory service: sync episodic ingest and hybrid search.
type EngramServer interface {
	// Ingest durably appends one event to episodic memory and returns its
	// storage id. The append is the enqueue: extraction and reconciliation
	// happen asynchronously (D4/D12). event_id is required; replays of the
	// same event_id are idempotent end-to-end via the extraction ledger (D13).
	Ingest(context.Context, *IngestRequest) (*IngestResponse, error)
	// Search runs one hybrid query (BM25 + kNN -> RRF) and returns a single
	// fused, ranked hit list.
	Search(context.Context, *SearchRequest) (*SearchResponse, error)
	// Status reports server health, the caller's resolved identity, and coarse
	// tier document counts — the backing RPC for `engram status` and the MCP
	// memory_status tool. It requires a valid token like every other call.
	Status(context.Context, *StatusRequest) (*StatusResponse, error)
	// Audit returns a fact's provenance (who wrote it, from what) and its full
	// bi-temporal version history (Phase 4, DW-4.6) — the backing RPC for
	// `engram audit <id>`. The caller must be authorized to READ the target
	// fact; an unauthorized or unknown id returns NOT_FOUND (no existence
	// oracle). Scope enforcement applies here exactly as it does to search.
	Audit(context.Context, *AuditRequest) (*AuditResponse, error)
	mustEmbedUnimplementedEngramServer()
}

// UnimplementedEngramServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEngramServer struct{}

func (UnimplementedEngramServer) Ingest(context.Context, *IngestRequest) (*IngestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ingest not implemented")
}
func (UnimplementedEngramServer) Search(context.Context, *SearchRequest) (*SearchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Search not implemented")
}
func (UnimplementedEngramServer) Status(context.Context, *StatusRequest) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Status not implemented")
}
func (UnimplementedEngramServer) Audit(context.Context, *AuditRequest) (*AuditResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Audit not implemented")
}
func (UnimplementedEngramServer) mustEmbedUnimplementedEngramServer() {}
func (UnimplementedEngramServer) testEmbeddedByValue()                {}

// UnsafeEngramServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EngramServer will
// result in compilation errors.
type UnsafeEngramServer interface {
	mustEmbedUnimplementedEngramServer()
}

func RegisterEngramServer(s grpc.ServiceRegistrar, srv EngramServer) {
	// If the following call pancis, it indicates UnimplementedEngramServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Engram_ServiceDesc, srv)
}

func _Engram_Ingest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IngestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngramServer).Ingest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Engram_Ingest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngramServer).Ingest(ctx, req.(*IngestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Engram_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngramServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Engram_Search_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngramServer).Search(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Engram_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngramServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Engram_Status_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngramServer).Status(ctx, req.(*StatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Engram_Audit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuditRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngramServer).Audit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Engram_Audit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngramServer).Audit(ctx, req.(*AuditRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Engram_ServiceDesc is the grpc.ServiceDesc for Engram service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Engram_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "engram.v1.Engram",
	HandlerType: (*EngramServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ingest",
			Handler:    _Engram_Ingest_Handler,
		},
		{
			MethodName: "Search",
			Handler:    _Engram_Search_Handler,
		},
		{
			MethodName: "Status",
			Handler:    _Engram_Status_Handler,
		},
		{
			MethodName: "Audit",
			Handler:    _Engram_Audit_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "engram.proto",
}
