// Engram service contract (walking-skeleton seam, locked in Phase 0).
//
// Ingest is the sync episodic append: cheap, durable, and the enqueue for the
// async write path (outbox, D12). event_id is REQUIRED — it is the client-
// supplied idempotency identity (D13); the server rejects an empty event_id
// with INVALID_ARGUMENT. proto3 cannot express required fields, so the
// requirement is enforced server-side and documented here.
//
// Search is the hybrid read path: BM25 + kNN fused by RRF (D1), scoped by
// tenancy filters (D16) and the bi-temporal current-state filter (D3).
//
// Authentication (Phase 3): every RPC is authenticated by a bearer token in
// the gRPC `authorization` metadata header, value "Bearer <raw-token>". A
// unary interceptor (the barricade) verifies the token, resolves the bound
// Identity{tenant_id, user_id, agent_id}, and injects it; unauthenticated
// calls are rejected with codes.Unauthenticated and an opaque message (no
// detail leak). The server derives tenancy/provenance from the resolved
// Identity, not from client-supplied fields, so a token cannot act outside
// its binding.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: engram.proto

package engrampb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Engram_Ingest_FullMethodName               = "/engram.v1.Engram/Ingest"
	Engram_Search_FullMethodName               = "/engram.v1.Engram/Search"
	Engram_Status_FullMethodName               = "/engram.v1.Engram/Status"
	Engram_Audit_FullMethodName                = "/engram.v1.Engram/Audit"
	Engram_Read_FullMethodName                 = "/engram.v1.Engram/Read"
	Engram_Export_FullMethodName               = "/engram.v1.Engram/Export"
	Engram_MemoryPurge_FullMethodName          = "/engram.v1.Engram/MemoryPurge"
	Engram_KnowledgeIngest_FullMethodName      = "/engram.v1.Engram/KnowledgeIngest"
	Engram_KnowledgeSearch_FullMethodName      = "/engram.v1.Engram/KnowledgeSearch"
	Engram_KnowledgeCollections_FullMethodName = "/engram.v1.Engram/KnowledgeCollections"
	Engram_KnowledgeDelete_FullMethodName      = "/engram.v1.Engram/KnowledgeDelete"
	Engram_CreateCollection_FullMethodName     = "/engram.v1.Engram/CreateCollection"
	Engram_UpdateCollection_FullMethodName     = "/engram.v1.Engram/UpdateCollection"
)

// EngramClient is the client API for Engram service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Engram is the agent-memory service: sync episodic ingest and hybrid search.
type EngramClient interface {
	// Ingest durably appends one event to episodic memory and returns its
	// storage id. The append is the enqueue: extraction and reconciliation
	// happen asynchronously (D4/D12). event_id is required; replays of the
	// same event_id are idempotent end-to-end via the extraction ledger (D13).
	Ingest(ctx context.Context, in *IngestRequest, opts ...grpc.CallOption) (*IngestResponse, error)
	// Search runs one hybrid query (BM25 + kNN -> RRF) and returns a single
	// fused, ranked hit list.
	Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error)
	// Status reports server health, the caller's resolved identity, and coarse
	// tier document counts — the backing RPC for `engram status` and the MCP
	// memory_status tool. It requires a valid token like every other call.
	Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	// Audit returns a fact's provenance (who wrote it, from what) and its full
	// bi-temporal version history (Phase 4, DW-4.6) — the backing RPC for
	// `engram audit <id>`. The caller must be authorized to READ the target
	// fact; an unauthorized or unknown id returns NOT_FOUND (no existence
	// oracle). Scope enforcement applies here exactly as it does to search.
	Audit(ctx context.Context, in *AuditRequest, opts ...grpc.CallOption) (*AuditResponse, error)
	// Read returns ONE record's full content by (id, source) — the deliberate
	// drill-down behind the MCP memory_read tool. A full read spends the
	// caller's context, so it is a separate explicit call, never inlined into
	// Search. source selects the index dispatched to: "episodic" returns the
	// full raw event text, "semantic" returns the target fact version plus its
	// provenance and bi-temporal history (the Audit contract). Graph statements
	// are already whole in search hits, so "graph" is UNIMPLEMENTED. Read is a
	// by-id trust boundary: it runs the same fail-closed authorization as
	// Search/Audit — an unknown id, a cross-tenant record, an id/source
	// mismatch, or a record the caller may not read all return NOT_FOUND (no
	// existence oracle), and the handler never probes the other index.
	Read(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*ReadResponse, error)
	// Export returns one bounded page of the caller's tenant-scoped, live,
	// ACL-filtered graph (entities then edges) plus an opaque continuation
	// cursor — the backing RPC for `engram export <dir>`. The tenant is pinned
	// from the verified identity, never from the request; the cursor carries
	// NO tenancy and cannot reposition outside the caller's tenant. An empty
	// next_cursor means the graph is exhausted. Unary by design: it runs under
	// the same auth/telemetry interceptor chain as every other call.
	Export(ctx context.Context, in *ExportRequest, opts ...grpc.CallOption) (*ExportResponse, error)
	// MemoryPurge erases ingested events from the memory tier by event_id — the
	// one sanctioned escape hatch from append-only ingest, for undoing a bad
	// bulk migration. It is deliberately NOT a general retraction primitive
	// (that is an ordinary `retract:` ingest, which adds a fact rather than
	// removing one).
	//
	// Mixed hard/soft by tier, and per tier for a reason: the episodic log and
	// the extraction ledger (D13) are HARD-deleted, because neither has a
	// liveness filter on its read paths — a tombstone there would be invisible
	// to the outbox scan, export, and read. Semantic facts are SOFT-deleted by
	// stamping expired_at (the transaction-time close, D3), because hard-
	// deleting them would dangle the supersedes chains Audit walks.
	//
	// Purging by event_id removes EVERY episodic doc carrying that id, so the
	// replay duplicates a retried Ingest creates (event_id does not deduplicate
	// the raw log) all go together. The graph tier is not touched here: rebuild
	// it with the engram-graph-rebuild tool. dry_run (the recommended default
	// for callers) counts what would be removed and mutates nothing.
	//
	// Requires the memory-admin role; the tenant is taken from the caller's
	// verified token and can never be named in the request.
	MemoryPurge(ctx context.Context, in *MemoryPurgeRequest, opts ...grpc.CallOption) (*MemoryPurgeResponse, error)
	// KnowledgeIngest bulk-upserts one harvest batch of documents into a
	// collection. Rows are stamped server-side with harvest_id and harvested_at;
	// replays of the same document ids overwrite in place, so a failed batch is
	// safely retried whole.
	KnowledgeIngest(ctx context.Context, in *KnowledgeIngestRequest, opts ...grpc.CallOption) (*KnowledgeIngestResponse, error)
	// KnowledgeSearch runs one BM25 query over a collection's text field with
	// generic field filters and sort. No kNN, no RRF, no memory-tier fusion.
	KnowledgeSearch(ctx context.Context, in *KnowledgeSearchRequest, opts ...grpc.CallOption) (*KnowledgeSearchResponse, error)
	// KnowledgeCollections lists the collections the caller may read, each with
	// its field mappings (which fields are filterable/sortable), document count,
	// and staleness (newest harvested_at / newest document date).
	KnowledgeCollections(ctx context.Context, in *KnowledgeCollectionsRequest, opts ...grpc.CallOption) (*KnowledgeCollectionsResponse, error)
	// KnowledgeDelete is the mark-and-sweep sweep: it hard-deletes every row in
	// the collection from the named source whose harvest_id differs from
	// current_harvest_id (rows the latest harvest run did not touch).
	KnowledgeDelete(ctx context.Context, in *KnowledgeDeleteRequest, opts ...grpc.CallOption) (*KnowledgeDeleteResponse, error)
	// CreateCollection registers a new collection and provisions its backing
	// index live — no server restart. A duplicate name is ALREADY_EXISTS.
	CreateCollection(ctx context.Context, in *CreateCollectionRequest, opts ...grpc.CallOption) (*CreateCollectionResponse, error)
	// UpdateCollection amends an existing collection's spec (new fields, access
	// policy); the registry applies mapping changes live.
	UpdateCollection(ctx context.Context, in *UpdateCollectionRequest, opts ...grpc.CallOption) (*UpdateCollectionResponse, error)
}

type engramClient struct {
	cc grpc.ClientConnInterface
}

func NewEngramClient(cc grpc.ClientConnInterface) EngramClient {
	return &engramClient{cc}
}

func (c *engramClient) Ingest(ctx context.Context, in *IngestRequest, opts ...grpc.CallOption) (*IngestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IngestResponse)
	err := c.cc.Invoke(ctx, Engram_Ingest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engramClient) Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchResponse)
	err := c.cc.Invoke(ctx, Engram_Search_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engramClient) Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, Engram_Status_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engramClient) Audit(ctx context.Context, in *AuditRequest, opts ...grpc.CallOption) (*AuditResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuditResponse)
	err := c.cc.Invoke(ctx, Engram_Audit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engramClient) Read(ctx context.Context, in *ReadRequest, opts ...grpc.CallOption) (*ReadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadResponse)
	err := c.cc.Invoke(ctx, Engram_Read_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engramClient) Export(ctx context.Context, in *ExportRequest, opts ...grpc.CallOption) (*ExportResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExportResponse)
	err := c.cc.Invoke(ctx, Engram_Export_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engramClient) MemoryPurge(ctx context.Context, in *MemoryPurgeRequest, opts ...grpc.CallOption) (*MemoryPurgeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MemoryPurgeResponse)
	err := c.cc.Invoke(ctx, Engram_MemoryPurge_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engramClient) KnowledgeIngest(ctx context.Context, in *KnowledgeIngestRequest, opts ...grpc.CallOption) (*KnowledgeIngestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KnowledgeIngestResponse)
	err := c.cc.Invoke(ctx, Engram_KnowledgeIngest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engramClient) KnowledgeSearch(ctx context.Context, in *KnowledgeSearchRequest, opts ...grpc.CallOption) (*KnowledgeSearchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KnowledgeSearchResponse)
	err := c.cc.Invoke(ctx, Engram_KnowledgeSearch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engramClient) KnowledgeCollections(ctx context.Context, in *KnowledgeCollectionsRequest, opts ...grpc.CallOption) (*KnowledgeCollectionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KnowledgeCollectionsResponse)
	err := c.cc.Invoke(ctx, Engram_KnowledgeCollections_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engramClient) KnowledgeDelete(ctx context.Context, in *KnowledgeDeleteRequest, opts ...grpc.CallOption) (*KnowledgeDeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KnowledgeDeleteResponse)
	err := c.cc.Invoke(ctx, Engram_KnowledgeDelete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engramClient) CreateCollection(ctx context.Context, in *CreateCollectionRequest, opts ...grpc.CallOption) (*CreateCollectionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateCollectionResponse)
	err := c.cc.Invoke(ctx, Engram_CreateCollection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engramClient) UpdateCollection(ctx context.Context, in *UpdateCollectionRequest, opts ...grpc.CallOption) (*UpdateCollectionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateCollectionResponse)
	err := c.cc.Invoke(ctx, Engram_UpdateCollection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EngramServer is the server API for Engram service.
// All implementations must embed UnimplementedEngramServer
// for forward compatibility.
//
// Engram is the agent-memory service: sync episodic ingest and hybrid search.
type EngramServer interface {
	// Ingest durably appends one event to episodic memory and returns its
	// storage id. The append is the enqueue: extraction and reconciliation
	// happen asynchronously (D4/D12). event_id is required; replays of the
	// same event_id are idempotent end-to-end via the extraction ledger (D13).
	Ingest(context.Context, *IngestRequest) (*IngestResponse, error)
	// Search runs one hybrid query (BM25 + kNN -> RRF) and returns a single
	// fused, ranked hit list.
	Search(context.Context, *SearchRequest) (*SearchResponse, error)
	// Status reports server health, the caller's resolved identity, and coarse
	// tier document counts — the backing RPC for `engram status` and the MCP
	// memory_status tool. It requires a valid token like every other call.
	Status(context.Context, *StatusRequest) (*StatusResponse, error)
	// Audit returns a fact's provenance (who wrote it, from what) and its full
	// bi-temporal version history (Phase 4, DW-4.6) — the backing RPC for
	// `engram audit <id>`. The caller must be authorized to READ the target
	// fact; an unauthorized or unknown id returns NOT_FOUND (no existence
	// oracle). Scope enforcement applies here exactly as it does to search.
	Audit(context.Context, *AuditRequest) (*AuditResponse, error)
	// Read returns ONE record's full content by (id, source) — the deliberate
	// drill-down behind the MCP memory_read tool. A full read spends the
	// caller's context, so it is a separate explicit call, never inlined into
	// Search. source selects the index dispatched to: "episodic" returns the
	// full raw event text, "semantic" returns the target fact version plus its
	// provenance and bi-temporal history (the Audit contract). Graph statements
	// are already whole in search hits, so "graph" is UNIMPLEMENTED. Read is a
	// by-id trust boundary: it runs the same fail-closed authorization as
	// Search/Audit — an unknown id, a cross-tenant record, an id/source
	// mismatch, or a record the caller may not read all return NOT_FOUND (no
	// existence oracle), and the handler never probes the other index.
	Read(context.Context, *ReadRequest) (*ReadResponse, error)
	// Export returns one bounded page of the caller's tenant-scoped, live,
	// ACL-filtered graph (entities then edges) plus an opaque continuation
	// cursor — the backing RPC for `engram export <dir>`. The tenant is pinned
	// from the verified identity, never from the request; the cursor carries
	// NO tenancy and cannot reposition outside the caller's tenant. An empty
	// next_cursor means the graph is exhausted. Unary by design: it runs under
	// the same auth/telemetry interceptor chain as every other call.
	Export(context.Context, *ExportRequest) (*ExportResponse, error)
	// MemoryPurge erases ingested events from the memory tier by event_id — the
	// one sanctioned escape hatch from append-only ingest, for undoing a bad
	// bulk migration. It is deliberately NOT a general retraction primitive
	// (that is an ordinary `retract:` ingest, which adds a fact rather than
	// removing one).
	//
	// Mixed hard/soft by tier, and per tier for a reason: the episodic log and
	// the extraction ledger (D13) are HARD-deleted, because neither has a
	// liveness filter on its read paths — a tombstone there would be invisible
	// to the outbox scan, export, and read. Semantic facts are SOFT-deleted by
	// stamping expired_at (the transaction-time close, D3), because hard-
	// deleting them would dangle the supersedes chains Audit walks.
	//
	// Purging by event_id removes EVERY episodic doc carrying that id, so the
	// replay duplicates a retried Ingest creates (event_id does not deduplicate
	// the raw log) all go together. The graph tier is not touched here: rebuild
	// it with the engram-graph-rebuild tool. dry_run (the recommended default
	// for callers) counts what would be removed and mutates nothing.
	//
	// Requires the memory-admin role; the tenant is taken from the caller's
	// verified token and can never be named in the request.
	MemoryPurge(context.Context, *MemoryPurgeRequest) (*MemoryPurgeResponse, error)
	// KnowledgeIngest bulk-upserts one harvest batch of documents into a
	// collection. Rows are stamped server-side with harvest_id and harvested_at;
	// replays of the same document ids overwrite in place, so a failed batch is
	// safely retried whole.
	KnowledgeIngest(context.Context, *KnowledgeIngestRequest) (*KnowledgeIngestResponse, error)
	// KnowledgeSearch runs one BM25 query over a collection's text field with
	// generic field filters and sort. No kNN, no RRF, no memory-tier fusion.
	KnowledgeSearch(context.Context, *KnowledgeSearchRequest) (*KnowledgeSearchResponse, error)
	// KnowledgeCollections lists the collections the caller may read, each with
	// its field mappings (which fields are filterable/sortable), document count,
	// and staleness (newest harvested_at / newest document date).
	KnowledgeCollections(context.Context, *KnowledgeCollectionsRequest) (*KnowledgeCollectionsResponse, error)
	// KnowledgeDelete is the mark-and-sweep sweep: it hard-deletes every row in
	// the collection from the named source whose harvest_id differs from
	// current_harvest_id (rows the latest harvest run did not touch).
	KnowledgeDelete(context.Context, *KnowledgeDeleteRequest) (*KnowledgeDeleteResponse, error)
	// CreateCollection registers a new collection and provisions its backing
	// index live — no server restart. A duplicate name is ALREADY_EXISTS.
	CreateCollection(context.Context, *CreateCollectionRequest) (*CreateCollectionResponse, error)
	// UpdateCollection amends an existing collection's spec (new fields, access
	// policy); the registry applies mapping changes live.
	UpdateCollection(context.Context, *UpdateCollectionRequest) (*UpdateCollectionResponse, error)
	mustEmbedUnimplementedEngramServer()
}

// UnimplementedEngramServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEngramServer struct{}

func (UnimplementedEngramServer) Ingest(context.Context, *IngestRequest) (*IngestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ingest not implemented")
}
func (UnimplementedEngramServer) Search(context.Context, *SearchRequest) (*SearchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Search not implemented")
}
func (UnimplementedEngramServer) Status(context.Context, *StatusRequest) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Status not implemented")
}
func (UnimplementedEngramServer) Audit(context.Context, *AuditRequest) (*AuditResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Audit not implemented")
}
func (UnimplementedEngramServer) Read(context.Context, *ReadRequest) (*ReadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Read not implemented")
}
func (UnimplementedEngramServer) Export(context.Context, *ExportRequest) (*ExportResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Export not implemented")
}
func (UnimplementedEngramServer) MemoryPurge(context.Context, *MemoryPurgeRequest) (*MemoryPurgeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MemoryPurge not implemented")
}
func (UnimplementedEngramServer) KnowledgeIngest(context.Context, *KnowledgeIngestRequest) (*KnowledgeIngestResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method KnowledgeIngest not implemented")
}
func (UnimplementedEngramServer) KnowledgeSearch(context.Context, *KnowledgeSearchRequest) (*KnowledgeSearchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method KnowledgeSearch not implemented")
}
func (UnimplementedEngramServer) KnowledgeCollections(context.Context, *KnowledgeCollectionsRequest) (*KnowledgeCollectionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method KnowledgeCollections not implemented")
}
func (UnimplementedEngramServer) KnowledgeDelete(context.Context, *KnowledgeDeleteRequest) (*KnowledgeDeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method KnowledgeDelete not implemented")
}
func (UnimplementedEngramServer) CreateCollection(context.Context, *CreateCollectionRequest) (*CreateCollectionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCollection not implemented")
}
func (UnimplementedEngramServer) UpdateCollection(context.Context, *UpdateCollectionRequest) (*UpdateCollectionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateCollection not implemented")
}
func (UnimplementedEngramServer) mustEmbedUnimplementedEngramServer() {}
func (UnimplementedEngramServer) testEmbeddedByValue()                {}

// UnsafeEngramServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EngramServer will
// result in compilation errors.
type UnsafeEngramServer interface {
	mustEmbedUnimplementedEngramServer()
}

func RegisterEngramServer(s grpc.ServiceRegistrar, srv EngramServer) {
	// If the following call pancis, it indicates UnimplementedEngramServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Engram_ServiceDesc, srv)
}

func _Engram_Ingest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IngestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngramServer).Ingest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Engram_Ingest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngramServer).Ingest(ctx, req.(*IngestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Engram_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngramServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Engram_Search_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngramServer).Search(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Engram_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngramServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Engram_Status_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngramServer).Status(ctx, req.(*StatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Engram_Audit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuditRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngramServer).Audit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Engram_Audit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngramServer).Audit(ctx, req.(*AuditRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Engram_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngramServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Engram_Read_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngramServer).Read(ctx, req.(*ReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Engram_Export_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngramServer).Export(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Engram_Export_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngramServer).Export(ctx, req.(*ExportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Engram_MemoryPurge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MemoryPurgeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngramServer).MemoryPurge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Engram_MemoryPurge_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngramServer).MemoryPurge(ctx, req.(*MemoryPurgeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Engram_KnowledgeIngest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KnowledgeIngestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngramServer).KnowledgeIngest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Engram_KnowledgeIngest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngramServer).KnowledgeIngest(ctx, req.(*KnowledgeIngestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Engram_KnowledgeSearch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KnowledgeSearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngramServer).KnowledgeSearch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Engram_KnowledgeSearch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngramServer).KnowledgeSearch(ctx, req.(*KnowledgeSearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Engram_KnowledgeCollections_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KnowledgeCollectionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngramServer).KnowledgeCollections(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Engram_KnowledgeCollections_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngramServer).KnowledgeCollections(ctx, req.(*KnowledgeCollectionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Engram_KnowledgeDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KnowledgeDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngramServer).KnowledgeDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Engram_KnowledgeDelete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngramServer).KnowledgeDelete(ctx, req.(*KnowledgeDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Engram_CreateCollection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCollectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngramServer).CreateCollection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Engram_CreateCollection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngramServer).CreateCollection(ctx, req.(*CreateCollectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Engram_UpdateCollection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCollectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngramServer).UpdateCollection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Engram_UpdateCollection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngramServer).UpdateCollection(ctx, req.(*UpdateCollectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Engram_ServiceDesc is the grpc.ServiceDesc for Engram service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Engram_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "engram.v1.Engram",
	HandlerType: (*EngramServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ingest",
			Handler:    _Engram_Ingest_Handler,
		},
		{
			MethodName: "Search",
			Handler:    _Engram_Search_Handler,
		},
		{
			MethodName: "Status",
			Handler:    _Engram_Status_Handler,
		},
		{
			MethodName: "Audit",
			Handler:    _Engram_Audit_Handler,
		},
		{
			MethodName: "Read",
			Handler:    _Engram_Read_Handler,
		},
		{
			MethodName: "Export",
			Handler:    _Engram_Export_Handler,
		},
		{
			MethodName: "MemoryPurge",
			Handler:    _Engram_MemoryPurge_Handler,
		},
		{
			MethodName: "KnowledgeIngest",
			Handler:    _Engram_KnowledgeIngest_Handler,
		},
		{
			MethodName: "KnowledgeSearch",
			Handler:    _Engram_KnowledgeSearch_Handler,
		},
		{
			MethodName: "KnowledgeCollections",
			Handler:    _Engram_KnowledgeCollections_Handler,
		},
		{
			MethodName: "KnowledgeDelete",
			Handler:    _Engram_KnowledgeDelete_Handler,
		},
		{
			MethodName: "CreateCollection",
			Handler:    _Engram_CreateCollection_Handler,
		},
		{
			MethodName: "UpdateCollection",
			Handler:    _Engram_UpdateCollection_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "engram.proto",
}
